@startuml

class FileManager {
  - cursor: FileSystem
  - commandFactory: CommandFactory
  + getCursor(): FileSystem
  + run(command: String): Result<FileManager>
  - getCommand(command: String): Command
}

interface FileSystem {
  + getName(): String
  + isDirectory(): boolean
  + copy(): FileSystem
}

FileManager --> FileSystem

class File {
  - name: String
}

FileSystem <|... File

interface CompositeFileSystem {
  + add(fileSystem: FileSystem): Result<FileSystem>
  + remove(fileSystem: FileSystem): Result<FileSystem>
  + getChildren(): List<FileSystem>
}

FileSystem <|.. CompositeFileSystem

class Directory {
  - name: String
  - files: List<FileSystem>
}

CompositeFileSystem <|.. Directory
FileSystem <--o Directory

class CommandFactory {
  - parser: Parser
  + getCommand(command: String): Command
  - parseCommand(params: String): List<String>
}

FileManager --> CommandFactory

class Parser {
  + parseCommand(params: String): List<String>
}

Parser <- CommandFactory

interface Command {
  + execute(): Result<FileManager>
}

CommandFactory --> Command

class LsCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

class CdCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

class TouchCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

class MkdirCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

class RmCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

class PwdCommand {
  - fileManager: FileManager
  - options: Map<String, String>
}

Command <|.. LsCommand
Command <|.. CdCommand
Command <|.. TouchCommand
Command <|.. MkdirCommand
Command <|.. RmCommand
Command <|.. PwdCommand

class Result<E> {
  + communication element
  - resultType: ResultType
  - value: E
  - message: String
  + getResultType(): String
  + getValue(): E
  + getMessage(): String
}

@enduml